import PillarPage from "@/components/PillarPage";
import { Link } from "@tanstack/react-router";
import { Button } from "@/components/ui/button";
import { ArrowRight } from "lucide-react";
import { WHATSAPP_URL } from "@/config/business";
import content from "@/content/singapore-pet-law.json";

export default function SingaporePetLawPage() {
return <PillarPage
  slug="singapore-pet-law"
  eyebrow="Singapore-anchored · Licensing, notices and contracts · Last reviewed October 2026"
  breadcrumbName="Singapore Pet Law"
  serviceType="Singapore Pet Law"
  serviceDescription="Singapore pet law counsel for pet owners and pet businesses: AVS licensing, bite notices and directions, Code of Animal Welfare updates for groomers and trainers, and pet business contracts, with English law advice on English-law governed contracts. Beyond Horizons by Bethel Chambers LLC. HL@beyondhorizons.sg."
  relatedHeading=""
  ctaHeading="Talk to pet law counsel"
  ctaBody="Send a short confidential outline of the notice, licence or contract and the key dates. We will come back with a practical next step where appropriate."
  lastUpdatedISO="2026-10-05"
  lastUpdatedLabel="October 2026"
  h1={content.h1} intro="" badges={[]} metaTitle={content.title} metaDescription={content.description} ogTitle={content.title} ogDescription={content.description}
  services={[]} updates={[]} relatedKeywords={[]}
  faqs={content.faqSchema.mainEntity.map(f => ({ q: f.name, a: f.acceptedAnswer.text }))}
  relatedPages={[{"label": "Singapore manufacturing and supply agreement counsel", "to": "/singapore-manufacturing-supply-agreements"}, {"label": "Commercial contracts counsel", "to": "/expertise/commercial-contracts"}, {"label": "Regulatory compliance counsel", "to": "/expertise/regulatory-compliance"}, {"label": "Singapore employment law counsel", "to": "/singapore-employment-law"}, {"label": "Meet Hui Ling Teo", "to": "/team/hui-ling-teo"}, {"label": "Beyond Horizons home", "to": "/"}]}
  editorial={{ entity: content.entity, note: "Beyond Horizons is a specialist practice group of Bethel Chambers LLC. Content is general information only, reflects Singapore law as at October 2026, and does not create a solicitor–client relationship.", intro: <>
<p className="text-muted-foreground leading-relaxed">{"Beyond Horizons by Bethel Chambers LLC (a specialist practice group of Bethel Chambers LLC) advises "}<strong className="font-semibold text-foreground">{"pet owners and pet businesses"}</strong>{" in Singapore on licensing, AVS and NParks notices, and the contracts and disputes that come with keeping, selling, boarding, grooming and training animals. Our work is "}<strong className="font-semibold text-foreground">{"Singapore-anchored"}</strong>{". Where a cross-border contract is governed by "}<strong className="font-semibold text-foreground">{"English law"}</strong>{", English law advice is given by Hui Ling Teo, who is qualified in England and Wales."}</p>
<p className="text-muted-foreground leading-relaxed">{"We are commercial and regulatory counsel. We help you read what a licence condition, written notice or direction actually requires, respond in an orderly way, and put sensible contracts in place with clients, suppliers and landlords. We are not a personal injury or criminal defence practice, and we do not campaign on animal welfare policy."}</p>
<p className="text-muted-foreground leading-relaxed">{"This page is general information about Singapore law as at October 2026. It is not advice on your situation and does not predict the outcome of any investigation, licence application or dispute."}</p>
</>, sections: <>
<section className="py-12 even:bg-secondary/20"><div className="container mx-auto px-6 max-w-4xl space-y-5"><h2 className="font-serif text-2xl md:text-3xl text-foreground mb-6">{"When to instruct pet law counsel"}</h2><ul className="list-disc pl-6 space-y-3 text-muted-foreground leading-relaxed"><li>{"You have received a written notice or direction from AVS or NParks about your dog or cat, for example after a reported bite"}</li><li>{"You run, or plan to open, a pet shop, boarding facility or breeding operation and need to understand the licence and its conditions"}</li><li>{"You run a grooming or dog training business and want your client terms, records and staff policies reviewed against the updated Code of Animal Welfare"}</li><li>{"Your licensed premises has received a written directive, or you are concerned about suspension or revocation of a licence"}</li><li>{"You are buying, selling or importing animals or pet products and want the contract checked"}</li><li>{"You have a contract dispute with a breeder, pet shop, boarding facility, groomer, trainer or veterinary clinic"}</li><li>{"Your pet was injured or died in someone else's care and you suspect the service was not provided as agreed"}</li><li>{"A cross-border contract involving pets or pet products is governed by English law"}</li></ul></div></section>
<section className="py-12 even:bg-secondary/20"><div className="container mx-auto px-6 max-w-4xl space-y-5"><h2 className="font-serif text-2xl md:text-3xl text-foreground mb-6">{"Licensing and the AVS / NParks interface"}</h2><p className="text-muted-foreground leading-relaxed">{"The "}<strong className="font-semibold text-foreground">{"Animals and Birds Act 1965"}</strong>{" is the main Singapore statute on animal health, movement, cruelty and welfare. It is administered by the National Parks Board (NParks) through the "}<strong className="font-semibold text-foreground">{"Director-General, Animal Health and Welfare"}</strong>{", and in practice through NParks' Animal and Veterinary Service (AVS)."}</p>
<p className="text-muted-foreground leading-relaxed">{"Two sets of rules under that Act matter most for the people this page is for:"}</p>
<ul className="list-disc pl-6 space-y-3 text-muted-foreground leading-relaxed"><li><strong className="font-semibold text-foreground">{"Animals and Birds (Licensing and Control of Cats and Dogs) Rules 2024"}</strong>{", in force from 1 September 2024 — licensing of pet cats and dogs, control requirements, and powers in bite cases. The Rules treat certain breeds as \"specified dogs\" with additional requirements; check the current Rules and AVS guidance before acquiring or relocating with such a dog."}</li><li><strong className="font-semibold text-foreground">{"Animals and Birds (Licensing of Premises for Pet Shop and Other Purposes) Rules"}</strong>{" — premises used as a pet shop, to exhibit or distribute pet animals or birds, or to breed, board or rear them for reward need a licence, subject to limited exceptions with conditions. The Director-General may issue written directives to licensees to safeguard animal health and welfare, and may issue further directives where a licence is suspended or revoked."}</li></ul>
<p className="text-muted-foreground leading-relaxed">{"How we help: reading licence conditions and directives against your operations, preparing a clear written response or plan, reviewing leases and supplier contracts that depend on a licence, and advising on what a suspension or revocation would mean for stock, clients and contracts. We do not file licence applications for you, and we cannot guarantee that a licence will be granted, renewed or kept. The Animals and Birds Act regime for pet-sector activities remains under review as at October 2026; check the current Rules and AVS guidance before relying on any summary on this page."}</p></div></section>
<section className="py-12 even:bg-secondary/20"><div className="container mx-auto px-6 max-w-4xl space-y-5"><h2 className="font-serif text-2xl md:text-3xl text-foreground mb-6">{"Dog and cat bite reports, notices and control directions"}</h2><p className="text-muted-foreground leading-relaxed">{"When a bite is reported, the 2024 Rules give the Director-General specific powers. In outline:"}</p>
<ol className="list-decimal pl-6 space-y-3 text-muted-foreground leading-relaxed"><li><strong className="font-semibold text-foreground">{"Reports from the person bitten."}</strong>{" The person who reports a bite to themselves, or to an animal in their care, may be asked for a medical or veterinary report."}</li><li><strong className="font-semibold text-foreground">{"Delivery for examination."}</strong>{" The Director-General or an authorised officer may, by written notice, direct the owner of a cat or dog reasonably believed to have bitten a person or another animal to deliver it, and related articles, to an authorised examiner at a stated time and place."}</li><li><strong className="font-semibold text-foreground">{"Control directions."}</strong>{" Having regard to the circumstances and the severity of the injury, the owner may be directed to secure the premises where the animal is kept and keep it under physical control when it leaves, and, for a dog, to meet further requirements in the Rules."}</li><li><strong className="font-semibold text-foreground">{"Compliance."}</strong>{" An owner given such a direction must comply with it."}</li></ol>
<p className="text-muted-foreground leading-relaxed">{"Counsel's role at this stage is practical: read the notice carefully, diarise what is required and by when, keep a clean written record, and make sure any statement you give is accurate and considered. Separate questions — a civil claim by the injured person, or any prosecution — may follow on their own tracks. We advise on the regulatory and contract side; for a mainly personal injury or criminal matter, see section 8."}</p></div></section>
<section className="py-12 even:bg-secondary/20"><div className="container mx-auto px-6 max-w-4xl space-y-5"><h2 className="font-serif text-2xl md:text-3xl text-foreground mb-6">{"Groomers and dog trainers: the October 2026 Code of Animal Welfare updates"}</h2><p className="text-muted-foreground leading-relaxed">{"On "}<strong className="font-semibold text-foreground">{"3 October 2026"}</strong>{", AVS updated the "}<strong className="font-semibold text-foreground">{"pet groomers annex"}</strong>{" of the Code of Animal Welfare (for the pet industry) and introduced a "}<strong className="font-semibold text-foreground">{"new annex for dog trainers"}</strong>{". Public reporting highlights closer supervision of animals throughout grooming sessions and, for trainers, a least intrusive, minimally aversive (LIMA) approach. Missing a Code minimum standard is not itself framed as a separate offence under the Code; AVS states that failure to meet the Code's minimum standards may be taken into account in animal welfare investigations."}</p>
<p className="text-muted-foreground leading-relaxed">{"For grooming and training businesses, this is a good moment to check:"}</p>
<ul className="list-disc pl-6 space-y-3 text-muted-foreground leading-relaxed"><li><strong className="font-semibold text-foreground">{"Client agreements"}</strong>{" — services offered and their limits, owner disclosures about health and temperament, emergency veterinary authority and cost, collection, payment and complaints"}</li><li><strong className="font-semibold text-foreground">{"Records"}</strong>{" — what you record about each session and how long you keep it"}</li><li><strong className="font-semibold text-foreground">{"Staff policies and contracts"}</strong>{" — supervision responsibilities, training, and what happens when standards are not met (see our "}<Link to="/singapore-employment-law" className="text-primary hover:underline">{"Singapore employment law counsel"}</Link>{" page for the employment side)"}</li><li><strong className="font-semibold text-foreground">{"Boarding"}</strong>{" — if you also board animals for reward, whether that activity needs a premises licence"}</li></ul>
<p className="text-muted-foreground leading-relaxed">{"We help you align your documents with the Code. We do not certify compliance, audit animal handling, or predict how AVS will view any particular incident."}</p></div></section>
<section className="py-12 even:bg-secondary/20"><div className="container mx-auto px-6 max-w-4xl space-y-5"><h2 className="font-serif text-2xl md:text-3xl text-foreground mb-6">{"Pet business and pet sale contracts"}</h2><ul className="list-disc pl-6 space-y-3 text-muted-foreground leading-relaxed"><li><strong className="font-semibold text-foreground">{"Boarding, grooming, training and daycare agreements"}</strong>{" with pet owners"}</li><li><strong className="font-semibold text-foreground">{"Sale and purchase of animals"}</strong>{" — a sale of an animal by a business may, depending on the facts, be treated as a sale of goods under the Sale of Goods Act 1979 (goods include personal chattels other than things in action and money), so the written terms, what was said about the animal, and terms implied by that Act may all matter, alongside any applicable consumer protection rules"}</li><li><strong className="font-semibold text-foreground">{"Breeder and pet shop terms"}</strong>{", including health information, returns and disclosures"}</li><li><strong className="font-semibold text-foreground">{"Leases and fit-out"}</strong>{" for licensed premises"}</li><li><strong className="font-semibold text-foreground">{"Supplier, distribution and private-label agreements"}</strong>{" for pet food, accessories and equipment — see "}<Link to="/singapore-manufacturing-supply-agreements" className="text-primary hover:underline">{"Singapore manufacturing and supply agreement counsel"}</Link></li><li><strong className="font-semibold text-foreground">{"Veterinary fee and service disputes"}</strong>{", from the contract side only: estimates, consent forms, invoices and service terms"}</li><li><strong className="font-semibold text-foreground">{"Exclusion and limitation clauses"}</strong>{" — Singapore law limits how far a business can exclude or restrict liability, especially with consumers, so we draft terms that are clear and realistic rather than one-sided"}</li></ul>
<p className="text-muted-foreground leading-relaxed">{"For general commercial drafting beyond pets, see "}<Link to="/expertise/$id" params={{ id: "commercial-contracts" }} className="text-primary hover:underline">{"Commercial contracts counsel"}</Link>{". For licensing and compliance programmes more broadly, see "}<Link to="/expertise/$id" params={{ id: "regulatory-compliance" }} className="text-primary hover:underline">{"Regulatory compliance counsel"}</Link>{"."}</p></div></section>
<section className="py-12 even:bg-secondary/20"><div className="container mx-auto px-6 max-w-4xl space-y-5"><h2 className="font-serif text-2xl md:text-3xl text-foreground mb-6">{"Cross-border and English-law contracts involving pets"}</h2><p className="text-muted-foreground leading-relaxed">{"Some pet-sector contracts cross borders: a pet product brand supplying Singapore under an English-law distribution agreement, a franchise or licence for a pet services concept, or a sale or transport arrangement with a party in England. Beyond Horizons advises on "}<strong className="font-semibold text-foreground">{"Singapore law and English law"}</strong>{". English law advice is given by Hui Ling Teo, who is qualified in England and Wales. We are not an English law firm. Singapore rules on licensing, import and animal welfare still apply to anything done in Singapore, whatever law governs the contract. We do not advise on the law of any other country; where another law applies, we coordinate with foreign counsel."}</p></div></section>
<section className="py-12 even:bg-secondary/20"><div className="container mx-auto px-6 max-w-4xl space-y-5"><h2 className="font-serif text-2xl md:text-3xl text-foreground mb-6">{"What we do not do"}</h2><ul className="list-disc pl-6 space-y-3 text-muted-foreground leading-relaxed"><li>{"We are "}<strong className="font-semibold text-foreground">{"not"}</strong>{" a personal injury or criminal defence practice. If your matter is mainly a personal injury claim or a criminal charge, we will say so early and coordinate with, or suggest that you instruct, appropriate counsel."}</li><li>{"We do "}<strong className="font-semibold text-foreground">{"not"}</strong>{" campaign on animal welfare policy or act as an animal welfare organisation."}</li><li>{"We do "}<strong className="font-semibold text-foreground">{"not"}</strong>{" file licence or permit applications, certify compliance, or give veterinary or animal-behaviour advice."}</li><li>{"We do "}<strong className="font-semibold text-foreground">{"not"}</strong>{" promise that a licence will be granted, that there will be no prosecution, that an animal will be returned, or that any sum will be recovered."}</li></ul></div></section>
<section className="py-12 even:bg-secondary/20"><div className="container mx-auto px-6 max-w-4xl space-y-5"><h2 className="font-serif text-2xl md:text-3xl text-foreground mb-6">{"How an instruction works"}</h2><p className="text-muted-foreground leading-relaxed">{"Send a short outline: who you are (owner or business), the animal or business involved, any notice, directive or contract, the key dates, and what you need. We screen conflicts first. Engagement is proposal-based. This page does not publish fees. Sending an email or booking a consultation does not create a solicitor–client relationship until terms are agreed."}</p>
<div className="flex flex-wrap items-center gap-5"><Button asChild><a href={WHATSAPP_URL} target="_blank" rel="noopener noreferrer">Schedule a consultation<ArrowRight className="ml-2 h-4 w-4" /></a></Button><a href="mailto:HL@beyondhorizons.sg" className="text-primary hover:underline">HL@beyondhorizons.sg</a></div></div></section>
</> }}
/>;
}
