import PillarPage from "@/components/PillarPage";
import { FileText, Users, Scale, Briefcase, Shield, Calendar } from "lucide-react";

export const employmentFaqs = [
  { question: "What laws govern employment in Singapore?", answer: "The Employment Act is the core statute, supplemented by the Employment of Foreign Manpower Act, Workplace Safety and Health Act, Industrial Relations Act, Retirement and Re-employment Act, and the Tripartite Guidelines issued by MOM, NTUC and SNEF." },
  { question: "Who is covered by the Singapore Employment Act?", answer: "Most employees under a contract of service are covered, including PMETs. Part IV (working hours, rest days, overtime) covers workmen earning up to S$4,500/month and non-workmen earning up to S$2,600/month. Domestic workers, seafarers and statutory board staff are excluded." },
  { question: "What are the rules on termination and notice in Singapore?", answer: "Either party may terminate with the contractual notice period (or payment in lieu). Without contractual notice, statutory minimums apply (1 day to 4 weeks depending on length of service). Wrongful dismissal claims go to the Tripartite Alliance for Dispute Management (TADM) and Employment Claims Tribunal." },
  { question: "How does retrenchment work under MOM guidelines?", answer: "Employers with 10+ employees must notify MOM of retrenchments within 5 working days. The Tripartite Advisory on Managing Excess Manpower recommends fair selection criteria, retrenchment benefits (typically 2 weeks to 1 month per year of service), and meaningful consultation. See our guide to <a href=\"/singapore-retrenchment-law\">retrenchment law in Singapore</a>." },
  { question: "What work passes does MOM issue?", answer: "The main categories are Employment Pass (EP), S Pass, Work Permit, Personalised Employment Pass (PEP), Tech.Pass, ONE Pass, EntrePass and Training EP. The Complementarity Assessment Framework (COMPASS) applies to EP applications from September 2023." },
  { question: "Are non-compete clauses enforceable in Singapore?", answer: "Restraint of trade clauses are presumptively unenforceable unless the employer can show a legitimate proprietary interest and that the restraint is reasonable in scope, duration and geography. The 2024 Tripartite Guidelines on Restrictive Covenants further tighten employer practice." },
  { question: "How is workplace harassment and discrimination handled?", answer: "The Protection from Harassment Act (POHA) provides civil and criminal remedies. The Workplace Fairness Act 2025 (passed 8 January 2025) and the Workplace Fairness (Dispute Resolution) Act 2025 (passed 4 November 2025), a separate Act that amends it, are not yet in force; MOM has said it aims for the legislation to take effect at the end of 2027. Once in force, the Workplace Fairness Act will prohibit employers from making adverse employment decisions based on protected characteristics: age; nationality; sex, marital status, pregnancy status and caregiving responsibilities; race, religion and language ability; and disability and mental health conditions. As passed, the Act does not apply (except for one provision, section 26) to employers with fewer than 25 employees, a number the Minister can change. MOM has said these small firms will be given more time before the requirements apply to them, that it will review this five years after the law is implemented, and that the Tripartite Guidelines on Fair Employment Practices continue to apply to them." },
  { question: "How does Beyond Horizons support cross-border employment matters?", answer: "We advise on Singapore employment contracts and disputes, plus cross-border issues — TUPE-style transfers, multi-jurisdiction restructurings, executive separations, investigations, work-pass strategy and people-side M&A — partnering with leading employment counsel in the relevant jurisdictions." },
  { question: "What is ONE Pass (AI and Tech), and how does it relate to Tech.Pass?", answer: "ONE Pass (AI and Tech) is a track under Singapore’s Overseas Networks & Expertise (ONE) Pass framework aimed at senior AI and tech talent. Under current MOM announcements, it is intended to replace Tech.Pass from January 2027, with more detail published on MOM’s channels as the launch approaches. Tech.Pass has been administered via EDB; EDB has said it will no longer accept new or renewal Tech.Pass applications from 28 January 2027. Existing Tech.Pass holders can typically stay on their pass until it expires, then consider ONE Pass (AI and Tech) or another suitable work pass. Always confirm dates and criteria on the official MOM and EDB pages before you file." },
  { question: "Can vested ESOP or ESOW count toward the ONE Pass (AI and Tech) salary criterion?", answer: "Under MOM’s March 2026 foreign-workforce factsheet framing, applicants on the ONE Pass (AI and Tech) track may meet the salary criterion through a combination of fixed cash salary and vested non-cash components such as ESOP/ESOW, subject to assessment — often described as a high overall monthly threshold with a minimum fixed cash component. Exact figures, valuation, and renewal rules can change; treat published MOM criteria as the source of truth and get counsel (and often mobility/tax input) before you rely on equity to qualify." },
  { question: "What should Singapore employers do before Tech.Pass sunsets?", answer: "Map who is on Tech.Pass or who you planned to hire on Tech.Pass. Diarise the January 2027 / late-January 2027 transition points. Compare ONE Pass (AI and Tech), Employment Pass (including COMPASS), and other options against role, salary mix, and family needs. Align offer letters and equity paperwork early if you expect non-cash components to matter. Employment counsel helps on contracts, pass strategy, and risk; pass filing is often handled with a MOM-licensed agency — the two roles are different." },
  { question: "When should we use employment counsel versus a MOM-licensed employment agency?", answer: "Agencies typically lead pass preparation and filing. Employment counsel is usually needed when you need privileged advice on offer and equity structuring, Workplace Fairness and AI-in-HR policies, workplace investigations, or executive exits across borders. Many Singapore employers use both: an agency for filing mechanics and counsel for the legal framework around the hire." },
  { question: "How should employers prepare AI hiring tools and HR use for the Workplace Fairness Act?", answer: "Treat AI-assisted screening, ranking, or people decisions as part of your fairness and documentation design — not only an IT project. Update handbooks, AI-in-HR policies, grievance routes, and vendor contracts so you can explain how tools are used and how humans review outcomes. Under the Workplace Fairness (Dispute Resolution) Act 2025, legal representation will not be allowed at mediation or in the Employment Claims Tribunals for workplace discrimination claims up to and including S$250,000, which raises the value of getting policies right before the Workplace Fairness Act takes effect (MOM has said it aims for the end of 2027). Confirm commencement on official channels; if useful, you can schedule a consultation. For GenAI/PDPC notification depth, see our AI Code Counsel pages." },
  { question: "Can employers bring lawyers to Workplace Fairness mediation or ECT claims up to S$250,000?", answer: "Under the Workplace Fairness (Dispute Resolution) Act 2025, which is not yet in force, parties cannot be represented by lawyers at mediation or in the Employment Claims Tribunals for workplace discrimination claims up to and including S$250,000; an employer that is a company may be represented by an officer or full-time employee, and union representation is allowed in specified cases. For claims above S$250,000, lawyers may act at mediation and the claim is heard in the High Court. That makes pre-dispute readiness — clear policies, fair process, and contemporaneous records — especially important. Exact representation rules follow the Act and any subsidiary legislation; confirm official MOM materials as commencement approaches. This is general information, not advice on any specific claim." },
  { question: "Does paying salary in lieu of notice defeat an Employment Act s14(2) wrongful-dismissal claim at the ECT?", answer: "Not automatically. Paying salary in lieu of notice does not by itself defeat an Employment Act wrongful-dismissal claim. Employers should keep contemporaneous performance records, clear role expectations, and a defensible process — especially for probationers or “no-reason” notice exits — and get counsel early when the exit is contested or cross-border. Themes from public 2026 ECT written decisions reinforce documentation discipline; this page does not summarise any specific case as Beyond Horizons advice. General information only." },
  { question: "What should outdoor-work employers know about heat-stress rules from December 2026?", answer: "MOM’s Heat Stress Management Framework describes mandatory workplace practices for outdoor-work employers from 1 December 2026. Growth companies whose workforce is mostly office-based may have lighter exposure, but contractors and site-facing teams should check the official MOM heat-stress guidance and align WSH policies early. Confirm details on MOM’s pages; counsel can help weave heat-stress duties into handbooks and contractor arrangements where relevant." },
  { question: "When should a Singapore growth company instruct employment counsel rather than relying on HR alone?", answer: "Instruct counsel for high-risk exits, workplace investigations, contested dismissals, cross-border executive separations, and Workplace Fairness programme design — not only routine handbook edits. HR remains essential for day-to-day people ops; counsel adds privileged advice and process design. Beyond Horizons by Bethel Chambers LLC acts as Singapore employment counsel for growth companies. Soft next step: schedule a consultation. Official MOM / Tripartite materials remain authoritative on statute text." },
  { question: "What does Workplace Fairness counsel help with (educational)?", answer: "Counsel helps interpret employer obligations for your facts — policies, AI-in-HR documentation, grievance routes, and pre-dispute readiness — without guaranteeing a regulatory outcome. Official guidance and the enacted framework remain the source of truth. Beyond Horizons by Bethel Chambers LLC. Soft next step: schedule a consultation. For GenAI/PDPC depth, see AI Code Counsel." },
  { question: "Can employment support sit alongside a fractional GC retainer?", answer: "Yes. Many growth companies pair employer-side employment work (contracts, exits, Workplace Fairness readiness) with ongoing fractional GC coverage for commercial and vendor matters. Beyond Horizons by Bethel Chambers LLC can scope either track or both in a proposal. Soft next step: schedule a consultation · fractional GC: https://beyondhorizons.sg/industry/fractional-gc" },
];

const SingaporeEmploymentLawPage = () => (
  <PillarPage
    slug="singapore-employment-law"
    eyebrow="Singapore-anchored · Cross-border Employment"
    h1="Singapore Employment Law Counsel — Workplace Fairness, Contracts & Exits"
    intro="Employer-side employment counsel for founders, CEOs, People and HR teams, and fractional GCs. We help Singapore employers prepare for Workplace Fairness, build contracts and policies, conduct investigations, and manage defensible exits across borders. Schedule a consultation when you need privileged advice on the legal framework around your workforce."
    badges={["MOM Compliance", "AI Use Policy in HR decision making", "Executive Separations & Investigations"]}
    metaTitle="Singapore Employment Law Counsel | Workplace Fairness & Exits — Beyond Horizons"
    metaDescription="Employer-side employment counsel in Singapore — Workplace Fairness, contracts/policies, investigations, and exits. Book a consultation."
    ogTitle="Employment Law — Singapore-anchored, Cross-border Counsel"
    ogDescription="MOM compliance, work passes, terminations, retrenchments, restrictive covenants, and cross-border workforce strategy from Singapore."
    breadcrumbName="Singapore Employment Law"
    serviceType="Employment Law"
    serviceDescription="Singapore-anchored cross-border employment counsel — MOM compliance, work passes, terminations, retrenchments, executive compensation, and workplace investigations."
    callout={{ body: "Agencies typically lead pass preparation and filing. Employment counsel is usually needed when you need privileged advice on offer and equity structuring, Workplace Fairness and AI-in-HR policies, workplace investigations, or executive exits across borders. Many Singapore employers use both: an agency for filing mechanics and counsel for the legal framework around the hire." }}
    services={[
      { icon: FileText, title: "Employment Contracts & Policies", desc: "Bespoke employment agreements, executive service contracts, handbooks, IP and confidentiality, restrictive covenants aligned with the 2024 Tripartite Guidelines — designed for multi-jurisdiction roll-out." },
      { icon: Users, title: "Work Passes & Global Mobility", desc: "EP, S Pass, ONE Pass and EntrePass strategy — including COMPASS optimisation, dependant arrangements and senior-leader relocation. From 2027, plan for the ONE Pass (AI and Tech) track that replaces Tech.Pass for eligible AI and tech talent (see FAQs)." },
      { icon: Briefcase, title: "Terminations & Retrenchments", desc: "Performance exits, summary dismissals, mutual separations, mass retrenchments and MOM notifications under the Tripartite Advisory on Managing Excess Manpower — coordinated with overseas employment counsel." },
      { icon: Scale, title: "Disputes & Investigations", desc: "Wrongful dismissal, TADM mediation, Employment Claims Tribunal, workplace harassment investigations, and confidential cross-border probes for boards and audit committees." },
      { icon: Shield, title: "Workplace Fairness & Harassment", desc: "Workplace Fairness Act readiness, POHA-compliant grievance handling, anti-discrimination policy design and training for managers across regional offices." },
      { icon: Calendar, title: "M&A and Restructuring People Issues", desc: "Workforce transfers in M&A, harmonisation of terms, equity rollover, change-in-control treatment and post-deal integration — including cross-border carve-outs." },
    ]}
    contentSections={[
      { heading: "Contracts, handbooks & AI-in-HR under Workplace Fairness", paragraphs: ["We advise on employment agreements, restrictive covenants under the Tripartite Guidelines framing, handbooks, grievance design, and AI Use Policies for hiring and people decisions. Under the Workplace Fairness (Dispute Resolution) Act 2025, a separate Act that amends the Workplace Fairness Act 2025 to provide for mediation of workplace fairness disputes and civil claims for discrimination, workplace discrimination claims up to and including S$250,000 will be heard in the Employment Claims Tribunals, where legal representation is not allowed, and lawyers cannot represent parties at the required mediation for claims at that level. Neither Act is in force yet, and MOM has said it aims for the legislation to take effect at the end of 2027, so policies, fair process, and documentation matter before a dispute begins. Confirm commencement and representation rules in official MOM materials."], links: [{ label: "AI Code Counsel", to: "/industry/ai-code-counsel" }, { label: "Singapore AI Governance", to: "/singapore-ai-governance" }] },
      { heading: "Exits, investigations & ECT documentation", paragraphs: ["We support mutual separations, retrenchments, workplace investigations, and contested or cross-border exits. Employment Act s14(2) and public ECT written-decision themes reinforce contemporaneous performance records, clear role expectations, and a defensible process. Salary in lieu of notice does not automatically defeat a wrongful-dismissal claim, so employers should seek counsel early where an exit is disputed." ] },
      { heading: "Heat stress / outdoor WSH", paragraphs: ["MOM’s Heat Stress Management Framework describes mandatory practices from 1 December 2026 for outdoor-work employers. Office-based growth companies may have lighter exposure, but site-facing teams and contractor arrangements should be checked against current MOM guidance before the date." ] },
    ]}
    updates={[
      { title: "Workplace Fairness Legislation", summary: "Singapore's Workplace Fairness Act 2025, together with the Workplace Fairness (Dispute Resolution) Act 2025, will introduce statutory protections against discrimination across protected characteristics, plus mandatory grievance handling and tribunal access. Both have been passed but are not yet in force; MOM has said it aims for the legislation to take effect at the end of 2027." },
      { title: "Platform Workers Act in force", summary: "Platform Workers Act extends CPF, work injury compensation and representation rights to ride-hail and delivery platform workers — reshaping the contractor / employee boundary." },
      { title: "COMPASS & EP framework refresh", summary: "MOM continues refining the Complementarity Assessment Framework, salary thresholds and Shortage Occupation List — material for any Singapore hiring plan." },
      { title: "ONE Pass (AI and Tech) replaces Tech.Pass", summary: "From January 2027, MOM’s ONE Pass (AI and Tech) track is intended to replace Tech.Pass for eligible AI and tech talent. EDB has stated it will stop accepting new and renewal Tech.Pass applications from 28 January 2027; existing Tech.Pass holders can usually remain until expiry. Employers should plan pass strategy early — criteria can be updated on MOM/EDB sites." },
    ]}
    faqs={employmentFaqs.map(({ question, answer }) => ({ q: question, a: answer }))}
    relatedKeywords={["employment", "mom", "workforce", "retrenchment", "work pass", "workplace", "labour", "labor", "hr"]}
    relatedHeading="Related Insights — Employment & Workforce"
    ctaHeading="Schedule an Employment Law Consultation"
    ctaBody="Whether you are restructuring a regional workforce, exiting a senior executive, or building a defensible employment framework, our team can help. Schedule a consultation or email HL@beyondhorizons.sg."
    exploreLink={{ label: "Explore our Employment Practice", to: "/expertise/employment-labor" }}
    relatedPages={[{ label: "Fractional GC for scale-ups", to: "/industry/fractional-gc" }, { label: "AI Code Counsel", to: "/industry/ai-code-counsel" }, { label: "Singapore AI Governance", to: "/singapore-ai-governance" }, { label: "Why Specialist Counsel", to: "/why-specialist-counsel" }]}
    lastUpdatedISO="2026-10-10"
    lastUpdatedLabel="September 2026"
  />
);

export default SingaporeEmploymentLawPage;
