/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AiToolsRouteImport } from './routes/ai-tools'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as AscendingAsiaRouteImport } from './routes/ascending-asia'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as JoinUsRouteImport } from './routes/join-us'
import { Route as MarketInsightsRouteImport } from './routes/market-insights'
import { Route as OurClientsRouteImport } from './routes/our-clients'
import { Route as SingaporeAiGovernanceRouteImport } from './routes/singapore-ai-governance'
import { Route as SingaporeAlternativeEnergyLawRouteImport } from './routes/singapore-alternative-energy-law'
import { Route as SingaporeAviationLawRouteImport } from './routes/singapore-aviation-law'
import { Route as SingaporeEmploymentLawRouteImport } from './routes/singapore-employment-law'
import { Route as SingaporeRestructuringInsolvencyRouteImport } from './routes/singapore-restructuring-insolvency'
import { Route as SingaporeRoboticsLawRouteImport } from './routes/singapore-robotics-law'
import { Route as SingaporeSpaceLawRouteImport } from './routes/singapore-space-law'
import { Route as TopicsRouteImport } from './routes/topics'
import { Route as WhySpecialistCounselRouteImport } from './routes/why-specialist-counsel'
import { Route as EnUsSplatRouteImport } from './routes/en-us/$'
import { Route as ExpertiseIndexRouteImport } from './routes/expertise/index'
import { Route as ExpertiseIdRouteImport } from './routes/expertise/$id'
import { Route as IndustryAiCodeCounselRouteImport } from './routes/industry/ai-code-counsel'
import { Route as IndustryAviationRouteImport } from './routes/industry/aviation'
import { Route as IndustryBlockchainDigitalAssetsRouteImport } from './routes/industry/blockchain-digital-assets'
import { Route as IndustryCybersecurityTechRouteImport } from './routes/industry/cybersecurity-tech'
import { Route as IndustryEnergyTransitionRouteImport } from './routes/industry/energy-transition'
import { Route as IndustryFractionalGcRouteImport } from './routes/industry/fractional-gc'
import { Route as IndustryRoboticsRouteImport } from './routes/industry/robotics'
import { Route as IndustrySpaceRouteImport } from './routes/industry/space'
import { Route as IndustryTradeTariffRouteImport } from './routes/industry/trade-tariff'
import { Route as IndustryTransportationRouteImport } from './routes/industry/transportation'
import { Route as IndustryWellnessHealthRouteImport } from './routes/industry/wellness-health'
import { Route as TeamIndexRouteImport } from './routes/team/index'
import { Route as TeamSlugRouteImport } from './routes/team/$slug'
import { Route as WhyChooseUsIdRouteImport } from './routes/why-choose-us/$id'
import { Route as WorkIndexRouteImport } from './routes/work/index'
import { Route as WorkCsrRouteImport } from './routes/work/csr'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AiToolsRoute = AiToolsRouteImport.update({
  id: '/ai-tools',
  path: '/ai-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AscendingAsiaRoute = AscendingAsiaRouteImport.update({
  id: '/ascending-asia',
  path: '/ascending-asia',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinUsRoute = JoinUsRouteImport.update({
  id: '/join-us',
  path: '/join-us',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketInsightsRoute = MarketInsightsRouteImport.update({
  id: '/market-insights',
  path: '/market-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const OurClientsRoute = OurClientsRouteImport.update({
  id: '/our-clients',
  path: '/our-clients',
  getParentRoute: () => rootRouteImport,
} as any)
const SingaporeAiGovernanceRoute = SingaporeAiGovernanceRouteImport.update({
  id: '/singapore-ai-governance',
  path: '/singapore-ai-governance',
  getParentRoute: () => rootRouteImport,
} as any)
const SingaporeAlternativeEnergyLawRoute =
  SingaporeAlternativeEnergyLawRouteImport.update({
    id: '/singapore-alternative-energy-law',
    path: '/singapore-alternative-energy-law',
    getParentRoute: () => rootRouteImport,
  } as any)
const SingaporeAviationLawRoute = SingaporeAviationLawRouteImport.update({
  id: '/singapore-aviation-law',
  path: '/singapore-aviation-law',
  getParentRoute: () => rootRouteImport,
} as any)
const SingaporeEmploymentLawRoute = SingaporeEmploymentLawRouteImport.update({
  id: '/singapore-employment-law',
  path: '/singapore-employment-law',
  getParentRoute: () => rootRouteImport,
} as any)
const SingaporeRestructuringInsolvencyRoute =
  SingaporeRestructuringInsolvencyRouteImport.update({
    id: '/singapore-restructuring-insolvency',
    path: '/singapore-restructuring-insolvency',
    getParentRoute: () => rootRouteImport,
  } as any)
const SingaporeRoboticsLawRoute = SingaporeRoboticsLawRouteImport.update({
  id: '/singapore-robotics-law',
  path: '/singapore-robotics-law',
  getParentRoute: () => rootRouteImport,
} as any)
const SingaporeSpaceLawRoute = SingaporeSpaceLawRouteImport.update({
  id: '/singapore-space-law',
  path: '/singapore-space-law',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsRoute = TopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => rootRouteImport,
} as any)
const WhySpecialistCounselRoute = WhySpecialistCounselRouteImport.update({
  id: '/why-specialist-counsel',
  path: '/why-specialist-counsel',
  getParentRoute: () => rootRouteImport,
} as any)
const EnUsSplatRoute = EnUsSplatRouteImport.update({
  id: '/en-us/$',
  path: '/en-us/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertiseIndexRoute = ExpertiseIndexRouteImport.update({
  id: '/expertise/',
  path: '/expertise/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertiseIdRoute = ExpertiseIdRouteImport.update({
  id: '/expertise/$id',
  path: '/expertise/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryAiCodeCounselRoute = IndustryAiCodeCounselRouteImport.update({
  id: '/industry/ai-code-counsel',
  path: '/industry/ai-code-counsel',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryAviationRoute = IndustryAviationRouteImport.update({
  id: '/industry/aviation',
  path: '/industry/aviation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryBlockchainDigitalAssetsRoute =
  IndustryBlockchainDigitalAssetsRouteImport.update({
    id: '/industry/blockchain-digital-assets',
    path: '/industry/blockchain-digital-assets',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndustryCybersecurityTechRoute =
  IndustryCybersecurityTechRouteImport.update({
    id: '/industry/cybersecurity-tech',
    path: '/industry/cybersecurity-tech',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndustryEnergyTransitionRoute =
  IndustryEnergyTransitionRouteImport.update({
    id: '/industry/energy-transition',
    path: '/industry/energy-transition',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndustryFractionalGcRoute = IndustryFractionalGcRouteImport.update({
  id: '/industry/fractional-gc',
  path: '/industry/fractional-gc',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryRoboticsRoute = IndustryRoboticsRouteImport.update({
  id: '/industry/robotics',
  path: '/industry/robotics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustrySpaceRoute = IndustrySpaceRouteImport.update({
  id: '/industry/space',
  path: '/industry/space',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryTradeTariffRoute = IndustryTradeTariffRouteImport.update({
  id: '/industry/trade-tariff',
  path: '/industry/trade-tariff',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryTransportationRoute = IndustryTransportationRouteImport.update({
  id: '/industry/transportation',
  path: '/industry/transportation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryWellnessHealthRoute = IndustryWellnessHealthRouteImport.update({
  id: '/industry/wellness-health',
  path: '/industry/wellness-health',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamIndexRoute = TeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamSlugRoute = TeamSlugRouteImport.update({
  id: '/team/$slug',
  path: '/team/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyChooseUsIdRoute = WhyChooseUsIdRouteImport.update({
  id: '/why-choose-us/$id',
  path: '/why-choose-us/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/work/',
  path: '/work/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkCsrRoute = WorkCsrRouteImport.update({
  id: '/work/csr',
  path: '/work/csr',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-tools': typeof AiToolsRoute
  '/announcements': typeof AnnouncementsRoute
  '/ascending-asia': typeof AscendingAsiaRoute
  '/courses': typeof CoursesRoute
  '/join-us': typeof JoinUsRoute
  '/market-insights': typeof MarketInsightsRoute
  '/our-clients': typeof OurClientsRoute
  '/singapore-ai-governance': typeof SingaporeAiGovernanceRoute
  '/singapore-alternative-energy-law': typeof SingaporeAlternativeEnergyLawRoute
  '/singapore-aviation-law': typeof SingaporeAviationLawRoute
  '/singapore-employment-law': typeof SingaporeEmploymentLawRoute
  '/singapore-restructuring-insolvency': typeof SingaporeRestructuringInsolvencyRoute
  '/singapore-robotics-law': typeof SingaporeRoboticsLawRoute
  '/singapore-space-law': typeof SingaporeSpaceLawRoute
  '/topics': typeof TopicsRoute
  '/why-specialist-counsel': typeof WhySpecialistCounselRoute
  '/en-us/$': typeof EnUsSplatRoute
  '/expertise/$id': typeof ExpertiseIdRoute
  '/industry/ai-code-counsel': typeof IndustryAiCodeCounselRoute
  '/industry/aviation': typeof IndustryAviationRoute
  '/industry/blockchain-digital-assets': typeof IndustryBlockchainDigitalAssetsRoute
  '/industry/cybersecurity-tech': typeof IndustryCybersecurityTechRoute
  '/industry/energy-transition': typeof IndustryEnergyTransitionRoute
  '/industry/fractional-gc': typeof IndustryFractionalGcRoute
  '/industry/robotics': typeof IndustryRoboticsRoute
  '/industry/space': typeof IndustrySpaceRoute
  '/industry/trade-tariff': typeof IndustryTradeTariffRoute
  '/industry/transportation': typeof IndustryTransportationRoute
  '/industry/wellness-health': typeof IndustryWellnessHealthRoute
  '/team/$slug': typeof TeamSlugRoute
  '/why-choose-us/$id': typeof WhyChooseUsIdRoute
  '/work/csr': typeof WorkCsrRoute
  '/expertise/': typeof ExpertiseIndexRoute
  '/team/': typeof TeamIndexRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-tools': typeof AiToolsRoute
  '/announcements': typeof AnnouncementsRoute
  '/ascending-asia': typeof AscendingAsiaRoute
  '/courses': typeof CoursesRoute
  '/join-us': typeof JoinUsRoute
  '/market-insights': typeof MarketInsightsRoute
  '/our-clients': typeof OurClientsRoute
  '/singapore-ai-governance': typeof SingaporeAiGovernanceRoute
  '/singapore-alternative-energy-law': typeof SingaporeAlternativeEnergyLawRoute
  '/singapore-aviation-law': typeof SingaporeAviationLawRoute
  '/singapore-employment-law': typeof SingaporeEmploymentLawRoute
  '/singapore-restructuring-insolvency': typeof SingaporeRestructuringInsolvencyRoute
  '/singapore-robotics-law': typeof SingaporeRoboticsLawRoute
  '/singapore-space-law': typeof SingaporeSpaceLawRoute
  '/topics': typeof TopicsRoute
  '/why-specialist-counsel': typeof WhySpecialistCounselRoute
  '/en-us/$': typeof EnUsSplatRoute
  '/expertise/$id': typeof ExpertiseIdRoute
  '/industry/ai-code-counsel': typeof IndustryAiCodeCounselRoute
  '/industry/aviation': typeof IndustryAviationRoute
  '/industry/blockchain-digital-assets': typeof IndustryBlockchainDigitalAssetsRoute
  '/industry/cybersecurity-tech': typeof IndustryCybersecurityTechRoute
  '/industry/energy-transition': typeof IndustryEnergyTransitionRoute
  '/industry/fractional-gc': typeof IndustryFractionalGcRoute
  '/industry/robotics': typeof IndustryRoboticsRoute
  '/industry/space': typeof IndustrySpaceRoute
  '/industry/trade-tariff': typeof IndustryTradeTariffRoute
  '/industry/transportation': typeof IndustryTransportationRoute
  '/industry/wellness-health': typeof IndustryWellnessHealthRoute
  '/team/$slug': typeof TeamSlugRoute
  '/why-choose-us/$id': typeof WhyChooseUsIdRoute
  '/work/csr': typeof WorkCsrRoute
  '/expertise': typeof ExpertiseIndexRoute
  '/team': typeof TeamIndexRoute
  '/work': typeof WorkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-tools': typeof AiToolsRoute
  '/announcements': typeof AnnouncementsRoute
  '/ascending-asia': typeof AscendingAsiaRoute
  '/courses': typeof CoursesRoute
  '/join-us': typeof JoinUsRoute
  '/market-insights': typeof MarketInsightsRoute
  '/our-clients': typeof OurClientsRoute
  '/singapore-ai-governance': typeof SingaporeAiGovernanceRoute
  '/singapore-alternative-energy-law': typeof SingaporeAlternativeEnergyLawRoute
  '/singapore-aviation-law': typeof SingaporeAviationLawRoute
  '/singapore-employment-law': typeof SingaporeEmploymentLawRoute
  '/singapore-restructuring-insolvency': typeof SingaporeRestructuringInsolvencyRoute
  '/singapore-robotics-law': typeof SingaporeRoboticsLawRoute
  '/singapore-space-law': typeof SingaporeSpaceLawRoute
  '/topics': typeof TopicsRoute
  '/why-specialist-counsel': typeof WhySpecialistCounselRoute
  '/en-us/$': typeof EnUsSplatRoute
  '/expertise/$id': typeof ExpertiseIdRoute
  '/industry/ai-code-counsel': typeof IndustryAiCodeCounselRoute
  '/industry/aviation': typeof IndustryAviationRoute
  '/industry/blockchain-digital-assets': typeof IndustryBlockchainDigitalAssetsRoute
  '/industry/cybersecurity-tech': typeof IndustryCybersecurityTechRoute
  '/industry/energy-transition': typeof IndustryEnergyTransitionRoute
  '/industry/fractional-gc': typeof IndustryFractionalGcRoute
  '/industry/robotics': typeof IndustryRoboticsRoute
  '/industry/space': typeof IndustrySpaceRoute
  '/industry/trade-tariff': typeof IndustryTradeTariffRoute
  '/industry/transportation': typeof IndustryTransportationRoute
  '/industry/wellness-health': typeof IndustryWellnessHealthRoute
  '/team/$slug': typeof TeamSlugRoute
  '/why-choose-us/$id': typeof WhyChooseUsIdRoute
  '/work/csr': typeof WorkCsrRoute
  '/expertise/': typeof ExpertiseIndexRoute
  '/team/': typeof TeamIndexRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-tools'
    | '/announcements'
    | '/ascending-asia'
    | '/courses'
    | '/join-us'
    | '/market-insights'
    | '/our-clients'
    | '/singapore-ai-governance'
    | '/singapore-alternative-energy-law'
    | '/singapore-aviation-law'
    | '/singapore-employment-law'
    | '/singapore-restructuring-insolvency'
    | '/singapore-robotics-law'
    | '/singapore-space-law'
    | '/topics'
    | '/why-specialist-counsel'
    | '/en-us/$'
    | '/expertise/$id'
    | '/industry/ai-code-counsel'
    | '/industry/aviation'
    | '/industry/blockchain-digital-assets'
    | '/industry/cybersecurity-tech'
    | '/industry/energy-transition'
    | '/industry/fractional-gc'
    | '/industry/robotics'
    | '/industry/space'
    | '/industry/trade-tariff'
    | '/industry/transportation'
    | '/industry/wellness-health'
    | '/team/$slug'
    | '/why-choose-us/$id'
    | '/work/csr'
    | '/expertise/'
    | '/team/'
    | '/work/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-tools'
    | '/announcements'
    | '/ascending-asia'
    | '/courses'
    | '/join-us'
    | '/market-insights'
    | '/our-clients'
    | '/singapore-ai-governance'
    | '/singapore-alternative-energy-law'
    | '/singapore-aviation-law'
    | '/singapore-employment-law'
    | '/singapore-restructuring-insolvency'
    | '/singapore-robotics-law'
    | '/singapore-space-law'
    | '/topics'
    | '/why-specialist-counsel'
    | '/en-us/$'
    | '/expertise/$id'
    | '/industry/ai-code-counsel'
    | '/industry/aviation'
    | '/industry/blockchain-digital-assets'
    | '/industry/cybersecurity-tech'
    | '/industry/energy-transition'
    | '/industry/fractional-gc'
    | '/industry/robotics'
    | '/industry/space'
    | '/industry/trade-tariff'
    | '/industry/transportation'
    | '/industry/wellness-health'
    | '/team/$slug'
    | '/why-choose-us/$id'
    | '/work/csr'
    | '/expertise'
    | '/team'
    | '/work'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-tools'
    | '/announcements'
    | '/ascending-asia'
    | '/courses'
    | '/join-us'
    | '/market-insights'
    | '/our-clients'
    | '/singapore-ai-governance'
    | '/singapore-alternative-energy-law'
    | '/singapore-aviation-law'
    | '/singapore-employment-law'
    | '/singapore-restructuring-insolvency'
    | '/singapore-robotics-law'
    | '/singapore-space-law'
    | '/topics'
    | '/why-specialist-counsel'
    | '/en-us/$'
    | '/expertise/$id'
    | '/industry/ai-code-counsel'
    | '/industry/aviation'
    | '/industry/blockchain-digital-assets'
    | '/industry/cybersecurity-tech'
    | '/industry/energy-transition'
    | '/industry/fractional-gc'
    | '/industry/robotics'
    | '/industry/space'
    | '/industry/trade-tariff'
    | '/industry/transportation'
    | '/industry/wellness-health'
    | '/team/$slug'
    | '/why-choose-us/$id'
    | '/work/csr'
    | '/expertise/'
    | '/team/'
    | '/work/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiToolsRoute: typeof AiToolsRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  AscendingAsiaRoute: typeof AscendingAsiaRoute
  CoursesRoute: typeof CoursesRoute
  JoinUsRoute: typeof JoinUsRoute
  MarketInsightsRoute: typeof MarketInsightsRoute
  OurClientsRoute: typeof OurClientsRoute
  SingaporeAiGovernanceRoute: typeof SingaporeAiGovernanceRoute
  SingaporeAlternativeEnergyLawRoute: typeof SingaporeAlternativeEnergyLawRoute
  SingaporeAviationLawRoute: typeof SingaporeAviationLawRoute
  SingaporeEmploymentLawRoute: typeof SingaporeEmploymentLawRoute
  SingaporeRestructuringInsolvencyRoute: typeof SingaporeRestructuringInsolvencyRoute
  SingaporeRoboticsLawRoute: typeof SingaporeRoboticsLawRoute
  SingaporeSpaceLawRoute: typeof SingaporeSpaceLawRoute
  TopicsRoute: typeof TopicsRoute
  WhySpecialistCounselRoute: typeof WhySpecialistCounselRoute
  EnUsSplatRoute: typeof EnUsSplatRoute
  ExpertiseIdRoute: typeof ExpertiseIdRoute
  IndustryAiCodeCounselRoute: typeof IndustryAiCodeCounselRoute
  IndustryAviationRoute: typeof IndustryAviationRoute
  IndustryBlockchainDigitalAssetsRoute: typeof IndustryBlockchainDigitalAssetsRoute
  IndustryCybersecurityTechRoute: typeof IndustryCybersecurityTechRoute
  IndustryEnergyTransitionRoute: typeof IndustryEnergyTransitionRoute
  IndustryFractionalGcRoute: typeof IndustryFractionalGcRoute
  IndustryRoboticsRoute: typeof IndustryRoboticsRoute
  IndustrySpaceRoute: typeof IndustrySpaceRoute
  IndustryTradeTariffRoute: typeof IndustryTradeTariffRoute
  IndustryTransportationRoute: typeof IndustryTransportationRoute
  IndustryWellnessHealthRoute: typeof IndustryWellnessHealthRoute
  TeamSlugRoute: typeof TeamSlugRoute
  WhyChooseUsIdRoute: typeof WhyChooseUsIdRoute
  WorkCsrRoute: typeof WorkCsrRoute
  ExpertiseIndexRoute: typeof ExpertiseIndexRoute
  TeamIndexRoute: typeof TeamIndexRoute
  WorkIndexRoute: typeof WorkIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-tools': {
      id: '/ai-tools'
      path: '/ai-tools'
      fullPath: '/ai-tools'
      preLoaderRoute: typeof AiToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ascending-asia': {
      id: '/ascending-asia'
      path: '/ascending-asia'
      fullPath: '/ascending-asia'
      preLoaderRoute: typeof AscendingAsiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-us': {
      id: '/join-us'
      path: '/join-us'
      fullPath: '/join-us'
      preLoaderRoute: typeof JoinUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market-insights': {
      id: '/market-insights'
      path: '/market-insights'
      fullPath: '/market-insights'
      preLoaderRoute: typeof MarketInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-clients': {
      id: '/our-clients'
      path: '/our-clients'
      fullPath: '/our-clients'
      preLoaderRoute: typeof OurClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/singapore-ai-governance': {
      id: '/singapore-ai-governance'
      path: '/singapore-ai-governance'
      fullPath: '/singapore-ai-governance'
      preLoaderRoute: typeof SingaporeAiGovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/singapore-alternative-energy-law': {
      id: '/singapore-alternative-energy-law'
      path: '/singapore-alternative-energy-law'
      fullPath: '/singapore-alternative-energy-law'
      preLoaderRoute: typeof SingaporeAlternativeEnergyLawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/singapore-aviation-law': {
      id: '/singapore-aviation-law'
      path: '/singapore-aviation-law'
      fullPath: '/singapore-aviation-law'
      preLoaderRoute: typeof SingaporeAviationLawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/singapore-employment-law': {
      id: '/singapore-employment-law'
      path: '/singapore-employment-law'
      fullPath: '/singapore-employment-law'
      preLoaderRoute: typeof SingaporeEmploymentLawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/singapore-restructuring-insolvency': {
      id: '/singapore-restructuring-insolvency'
      path: '/singapore-restructuring-insolvency'
      fullPath: '/singapore-restructuring-insolvency'
      preLoaderRoute: typeof SingaporeRestructuringInsolvencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/singapore-robotics-law': {
      id: '/singapore-robotics-law'
      path: '/singapore-robotics-law'
      fullPath: '/singapore-robotics-law'
      preLoaderRoute: typeof SingaporeRoboticsLawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/singapore-space-law': {
      id: '/singapore-space-law'
      path: '/singapore-space-law'
      fullPath: '/singapore-space-law'
      preLoaderRoute: typeof SingaporeSpaceLawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics': {
      id: '/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof TopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-specialist-counsel': {
      id: '/why-specialist-counsel'
      path: '/why-specialist-counsel'
      fullPath: '/why-specialist-counsel'
      preLoaderRoute: typeof WhySpecialistCounselRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en-us/$': {
      id: '/en-us/$'
      path: '/en-us/$'
      fullPath: '/en-us/$'
      preLoaderRoute: typeof EnUsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expertise/': {
      id: '/expertise/'
      path: '/expertise'
      fullPath: '/expertise/'
      preLoaderRoute: typeof ExpertiseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expertise/$id': {
      id: '/expertise/$id'
      path: '/expertise/$id'
      fullPath: '/expertise/$id'
      preLoaderRoute: typeof ExpertiseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry/ai-code-counsel': {
      id: '/industry/ai-code-counsel'
      path: '/industry/ai-code-counsel'
      fullPath: '/industry/ai-code-counsel'
      preLoaderRoute: typeof IndustryAiCodeCounselRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry/aviation': {
      id: '/industry/aviation'
      path: '/industry/aviation'
      fullPath: '/industry/aviation'
      preLoaderRoute: typeof IndustryAviationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry/blockchain-digital-assets': {
      id: '/industry/blockchain-digital-assets'
      path: '/industry/blockchain-digital-assets'
      fullPath: '/industry/blockchain-digital-assets'
      preLoaderRoute: typeof IndustryBlockchainDigitalAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry/cybersecurity-tech': {
      id: '/industry/cybersecurity-tech'
      path: '/industry/cybersecurity-tech'
      fullPath: '/industry/cybersecurity-tech'
      preLoaderRoute: typeof IndustryCybersecurityTechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry/energy-transition': {
      id: '/industry/energy-transition'
      path: '/industry/energy-transition'
      fullPath: '/industry/energy-transition'
      preLoaderRoute: typeof IndustryEnergyTransitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry/fractional-gc': {
      id: '/industry/fractional-gc'
      path: '/industry/fractional-gc'
      fullPath: '/industry/fractional-gc'
      preLoaderRoute: typeof IndustryFractionalGcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry/robotics': {
      id: '/industry/robotics'
      path: '/industry/robotics'
      fullPath: '/industry/robotics'
      preLoaderRoute: typeof IndustryRoboticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry/space': {
      id: '/industry/space'
      path: '/industry/space'
      fullPath: '/industry/space'
      preLoaderRoute: typeof IndustrySpaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry/trade-tariff': {
      id: '/industry/trade-tariff'
      path: '/industry/trade-tariff'
      fullPath: '/industry/trade-tariff'
      preLoaderRoute: typeof IndustryTradeTariffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry/transportation': {
      id: '/industry/transportation'
      path: '/industry/transportation'
      fullPath: '/industry/transportation'
      preLoaderRoute: typeof IndustryTransportationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry/wellness-health': {
      id: '/industry/wellness-health'
      path: '/industry/wellness-health'
      fullPath: '/industry/wellness-health'
      preLoaderRoute: typeof IndustryWellnessHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/': {
      id: '/team/'
      path: '/team'
      fullPath: '/team/'
      preLoaderRoute: typeof TeamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$slug': {
      id: '/team/$slug'
      path: '/team/$slug'
      fullPath: '/team/$slug'
      preLoaderRoute: typeof TeamSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-choose-us/$id': {
      id: '/why-choose-us/$id'
      path: '/why-choose-us/$id'
      fullPath: '/why-choose-us/$id'
      preLoaderRoute: typeof WhyChooseUsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/': {
      id: '/work/'
      path: '/work'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/csr': {
      id: '/work/csr'
      path: '/work/csr'
      fullPath: '/work/csr'
      preLoaderRoute: typeof WorkCsrRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiToolsRoute: AiToolsRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  AscendingAsiaRoute: AscendingAsiaRoute,
  CoursesRoute: CoursesRoute,
  JoinUsRoute: JoinUsRoute,
  MarketInsightsRoute: MarketInsightsRoute,
  OurClientsRoute: OurClientsRoute,
  SingaporeAiGovernanceRoute: SingaporeAiGovernanceRoute,
  SingaporeAlternativeEnergyLawRoute: SingaporeAlternativeEnergyLawRoute,
  SingaporeAviationLawRoute: SingaporeAviationLawRoute,
  SingaporeEmploymentLawRoute: SingaporeEmploymentLawRoute,
  SingaporeRestructuringInsolvencyRoute: SingaporeRestructuringInsolvencyRoute,
  SingaporeRoboticsLawRoute: SingaporeRoboticsLawRoute,
  SingaporeSpaceLawRoute: SingaporeSpaceLawRoute,
  TopicsRoute: TopicsRoute,
  WhySpecialistCounselRoute: WhySpecialistCounselRoute,
  EnUsSplatRoute: EnUsSplatRoute,
  ExpertiseIdRoute: ExpertiseIdRoute,
  IndustryAiCodeCounselRoute: IndustryAiCodeCounselRoute,
  IndustryAviationRoute: IndustryAviationRoute,
  IndustryBlockchainDigitalAssetsRoute: IndustryBlockchainDigitalAssetsRoute,
  IndustryCybersecurityTechRoute: IndustryCybersecurityTechRoute,
  IndustryEnergyTransitionRoute: IndustryEnergyTransitionRoute,
  IndustryFractionalGcRoute: IndustryFractionalGcRoute,
  IndustryRoboticsRoute: IndustryRoboticsRoute,
  IndustrySpaceRoute: IndustrySpaceRoute,
  IndustryTradeTariffRoute: IndustryTradeTariffRoute,
  IndustryTransportationRoute: IndustryTransportationRoute,
  IndustryWellnessHealthRoute: IndustryWellnessHealthRoute,
  TeamSlugRoute: TeamSlugRoute,
  WhyChooseUsIdRoute: WhyChooseUsIdRoute,
  WorkCsrRoute: WorkCsrRoute,
  ExpertiseIndexRoute: ExpertiseIndexRoute,
  TeamIndexRoute: TeamIndexRoute,
  WorkIndexRoute: WorkIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
